language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t oborisenko/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true oborisenko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-624360971490"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 



    http://dockerreact-env.eba-tsy72c2w.us-east-1.elasticbeanstalk.com/