language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t oborisenko/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true oborisenko/docker-react npm run test